# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  # Manually install certificates. Developers should run this when using a new machine.
  lane :install_certificates do
    match(
      type: 'development',
      app_identifier: ["ccrama.me.redditslide", "ccrama.me.redditslide.bundledwatchkitapp", "ccrama.me.redditslide.bundledwidgetconfigintent", "ccrama.me.redditslide.bundledwidgets", "ccrama.me.redditslide.bundledwatchkitapp.watchkitextension", "ccrama.me.redditslide.bundledOpen-in-Slide"]
    )
    match(
      type: 'appstore',
      app_identifier: ["ccrama.me.redditslide", "ccrama.me.redditslide.bundledwatchkitapp", "ccrama.me.redditslide.bundledwidgetconfigintent", "ccrama.me.redditslide.bundledwidgets", "ccrama.me.redditslide.bundledwatchkitapp.watchkitextension", "ccrama.me.redditslide.bundledOpen-in-Slide"]
    )
  end

  lane :beta do
    increment_build_number(xcodeproj: "Slide for Reddit.xcodeproj")
    match(
      readonly: true,
      type: 'appstore',
      app_identifier: ["ccrama.me.redditslide", "ccrama.me.redditslide.bundledwatchkitapp","ccrama.me.redditslide.bundledwidgets", "ccrama.me.redditslide.bundledwidgetconfigintent", "ccrama.me.redditslide.bundledwatchkitapp.watchkitextension", "ccrama.me.redditslide.bundledOpen-in-Slide"]
    )
    build_app(workspace: "Slide for Reddit.xcworkspace", scheme: "Slide for Reddit")
    upload_to_testflight
  end

  lane :beta14 do
    xcode_select('/Applications/Xcode-beta.app')
    increment_build_number(xcodeproj: "Slide for Reddit.xcodeproj")
    match(
      readonly: true,
      type: 'appstore',
      app_identifier: ["ccrama.me.redditslide", "ccrama.me.redditslide.bundledwatchkitapp","ccrama.me.redditslide.bundledwidgets", "ccrama.me.redditslide.bundledwidgetconfigintent", "ccrama.me.redditslide.bundledwatchkitapp.watchkitextension", "ccrama.me.redditslide.bundledOpen-in-Slide"]
    )
    build_app(workspace: "Slide for Reddit.xcworkspace", scheme: "Slide for Reddit")
    upload_to_testflight
  end
end

swiftlint(config_file: ".swiftlint.yml",
    strict: true,
    quiet: true,
    ignore_exit_status: true)

